import "./styles/fonts.css"; // Google Fonts for built-in themes
import "./styles/tokens.css"; // active theme — generated by scaffold (see THEMES.md)
import "./styles/base.css";
import "./styles/animations.css";

import { useCallback, useRef } from "react";
import { AutoStartGate } from "./components/AutoStartGate";
import { AutoToggle } from "./components/AutoToggle";
import { ProgressBar } from "./components/ProgressBar";
import { Stage } from "./components/Stage";
import { useAudioPlayer } from "./hooks/useAudioPlayer";
import { useAutoMode } from "./hooks/useAutoMode";
import { useStepTransition } from "./hooks/useStepTransition";
import { useStepper } from "./hooks/useStepper";
import { CHAPTERS } from "./registry/chapters";

const SCENE_TOPICS: Record<string, string> = {
  "real-problem": "LONG TASK BREAKPOINTS",
  "comet-positioning": "WHAT + HOW COMPOSITION",
  "five-stage-flow": "FIVE PHASE PIPELINE",
  "resume-entry": "RESUME ENTRYPOINT",
  "lightweight-state-machine": "LIGHTWEIGHT STATE",
  "install-and-routes": "INSTALL + ROUTES",
  "reference-value": "COMPOSITION PATTERN",
};

function estimateMs(text: string): number {
  if (!text) return 1500;
  return Math.max(1500, text.length * 250);
}

export default function App() {
  const stepper = useStepper(CHAPTERS);
  const ch = CHAPTERS[stepper.cursor.chapter]!;
  const Cmp = ch.Component;
  const stepText = ch.narrations[stepper.cursor.step] ?? "";
  const stepLabel = String(stepper.cursor.step + 1).padStart(2, "0");

  const { mode, cycleMode, autoStarted, setAutoStarted } = useAutoMode();
  const sceneRef = useRef<HTMLDivElement>(null);
  const { entranceOnly } = useStepTransition();

  const audioSrc =
    mode === "manual" || stepText === ""
      ? null
      : `${import.meta.env.BASE_URL}audio/${ch.id}/${stepper.cursor.step + 1}.mp3`;

  const onAutoAdvance = useCallback(() => stepper.next(), [stepper]);

  useAudioPlayer({
    src: audioSrc,
    mode,
    trailMs: 200,
    estimateFallbackMs: estimateMs(stepText),
    onAutoAdvance,
    autoStarted,
  });

  const handleAdvance = useCallback(() => {
    const el = sceneRef.current;
    if (el) {
      entranceOnly(el);
    }
    stepper.next();
  }, [stepper, entranceOnly]);

  return (
    <>
      <Stage onAdvance={handleAdvance}>
        <div className="scene-density-layer" aria-hidden="true" />
        <div
          key={`${ch.id}-${stepper.cursor.step}`}
          ref={sceneRef}
          className={`scene chapter-${ch.id} step-${stepper.cursor.step}`}
          data-topic={SCENE_TOPICS[ch.id] ?? ch.title}
          data-step={stepLabel}
        >
          <Cmp step={stepper.cursor.step} />
        </div>
      </Stage>
      <ProgressBar
        chapters={CHAPTERS}
        cursor={stepper.cursor}
        onJumpChapter={stepper.jumpToChapter}
      />
      <AutoToggle mode={mode} onCycle={cycleMode} />
      <AutoStartGate
        visible={mode === "auto" && !autoStarted}
        onStart={() => setAutoStarted(true)}
      />
    </>
  );
}
